class StampAcceptedCandidateDescriptions < ActiveRecord::Migration[8.0]
  # The stamp-based refresh scope treats an unstamped manual row as hand-written
  # seed editorial and never touches it. That's right for seed rows, but a legacy
  # approved-candidate row (source: manual, yet its copy was LLM-generated by
  # AiModelDescriptionJob) predates description_generated_at and so also carries a
  # nil stamp — leaving its generated copy frozen. Stamp those specific rows so
  # they rejoin the refresh cycle.
  #
  # The seam is slug: ModelCandidate#existing_model resolves a candidate to its
  # created AiModel by slug (there is no stored FK), and acceptance builds the row
  # with the candidate's slug — so an accepted candidate's slug identifies exactly
  # the row it created. Match on that, which distinguishes candidate rows from
  # hand-written seed rows without parsing db/seeds.rb. Stamp from created_at (the
  # description was generated just after the row was created), and only touch
  # written-up, still-unstamped rows so a re-run is a no-op.
  def up
    execute(<<~SQL.squish)
      UPDATE ai_models
      SET description_generated_at = created_at
      WHERE source = 'manual'
        AND description_generated_at IS NULL
        AND strengths IS NOT NULL AND strengths <> ''
        AND slug IN (SELECT slug FROM model_candidates WHERE status = 'accepted')
    SQL
  end

  def down
    # One-way data backfill; nothing meaningful to reverse.
  end
end
