# The display text of an event or launch "so what": one or two sentences on why
# something matters for someone pricing or choosing an LLM API. Generated by
# Claude and clamped so a runaway answer can't overflow a card, while a
# well-behaved two-sentence answer passes through untouched.
#
# The clamp is a guard, not the usual shape — so when it does trim, it ends on a
# sentence boundary if one sits reasonably deep in, and otherwise on a word
# boundary. It never cuts mid-word: a generated line should never *look*
# truncated (the same rule AiModel::Description follows).
module SoWhat
  LIMIT = 400

  def self.clamp(text)
    text = text.to_s.strip
    return text if text.length <= LIMIT

    window = text[0, LIMIT]
    sentence_end = window.rindex(/[.!?](?=\s|\z)/)
    if sentence_end && sentence_end >= LIMIT / 2
      window[0..sentence_end]
    else
      text.truncate(LIMIT, separator: /\s+/, omission: "…")
    end
  end
end
